### ISSUE TITLE
Push command error: peer 1 does not have channel 1

### ISSUE THREAD

**Issue by bruceleeroy18** [mit-dci/lit#130] opened 2017-12-24 15:08 UTC
Any suggestions to why this error is occuring? If I enter "push 1 50000" in lit-af, the following is returned, "Push error: peer 1 doesn't have channel 1"

Here is 'ls' info from node A. 

ls
entered command: ls
	Peers:
1 127.0.0.1:50148
	Channels:
Channel 1 (peer 1) type 1 00ad8f71a47dabbe6c9e6893aece37c4539a31e95a06933fed894f3ea3f81ed8;0
	 cap: 1000000 bal: 1000000 h: -1 state: 0
	Txos:
0 b3a09eb80ee7bf286b579d18dd3c2ee6a3ccfc9395788ecf71d3f1e9df4a1a33;0 h:1255786 amt:229983999 /44'/1'/0'/0'/0' testnet3
	Listening Ports:
Listening for connections on port(s) [:2448] with key ln1dle4yvnuxwyz4tlesvmlrueu6ttfuzsq6k0mra
	Addresses:
0 tb1qjtnrurhn5pgt8hgsqw82jlsgl0htjmpmag733l (mtugmasNhzGAwpuaRZYA8KVgqtHQaYQAyS)
1 tb1qzks0fl434c2a42365cga0j388tlhdm6rvfmfj2 (mhVKJa7LcdvTVoNYLaPsNRiGCTtQ9fF7tD)
2 tb1ql0022d7w9mw99q85jcv0ct9t53p7jf550pnt8c (n4Uicskd68tQSCCZp5MEi5Sa2cmo5YnpfZ)
	Type: 1	Sync Height: 1255844	FeeRate: 80	Utxo: 229983999	WitConf: 229983999 Channel: 1000000

**Comment by alindr** [comment] 2018-06-19 14:28
Is this still an issue?

**Comment by Varunram** [comment] 2018-06-19 14:29
I think this was caused by the outpoints not being registered. Should be solved with recent commits.

**Comment by bruceleeroy18** [comment] 2018-06-19 14:30
No. 


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: alindr <notifications@github.com> Date: 6/19/18  10:28  (GMT-05:00) To: mit-dci/lit <lit@noreply.github.com> Cc: bruceleeroy18 <browningsmith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [mit-dci/lit] Push command error: peer 1 does not have channel 1
  (#130) 
Is this still an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/mit-dci/lit/issues/130#issuecomment-398419229","url":"https://github.com/mit-dci/lit/issues/130#issuecomment-398419229","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mit-dci/lit","title":"mit-dci/lit","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mit-dci/lit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alindr in #130: Is this still an issue? "}],"action":{"name":"View Issue","url":"https://github.com/mit-dci/lit/issues/130#issuecomment-398419229"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mit-dci/lit] Push command error: peer 1 does not have channel 1 (#130)",
"sections": [
{
"text": "",
"activityTitle": "**alindr**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@alindr",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mit-dci/lit\",\n\"issueId\": 130,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mit-dci/lit\",\n\"issueId\": 130\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mit-dci/lit/issues/130#issuecomment-398419229"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 288344696\n}"
}
],
"themeColor": "26292E"
}

**Comment by gertjaap** [comment] 2018-06-27 23:21
Given that @bruceleeroy18 confirmed this issue is no longer existent, i'm closing this.

**Closed by gertjaap** 2018-06-27 23:21 UTC
