### ISSUE TITLE
Reconnect to other lit node automatically on startup and if we lose connection to them

### ISSUE THREAD

**Issue by alindr** [mit-dci/lit#199] opened 2018-06-13 21:25 UTC

**Comment by metalicjames** [comment] 2018-06-13 23:41
#182 was supposed to implement part of this but it appears to not work as intended:
```
decrypted message is 708e3661e6b65b3f9c95e4b97c90883799ef9e31f5423583f49ac6328e8d0f9ddf8b441ea2aad6bafb0000000000958940f1b913122991662c665558455c83f11f37eb9a010000001c000001b6
peerIdx is 1
routed bytes 708e3661e6b65b3f9c95e4b97c90883799ef9e31f5423583f49ac6328e8d0f9ddf8b441ea2aad6bafb0000000000958940f1b913122991662c665558455c83f11f37eb9a010000001c000001b6
message type 70
chanIdx is 0
type 70 97 bytes to peer 1
type 70 97 bytes to peer 1
read error with 1: read tcp 172.16.14.109:65144->5.196.74.100:2448: read: connection reset by peer

made session key dd5d64f8367f62bc75dceb350597e6b0af7fda8002515445d48770080753ac42
made idDH f739fc8fdbcc528d085d28b5b530b4e0e38360ea1f5b2bd406b151dbbb185b4e
type 70 97 bytes to peer 1
type 70 97 bytes to peer 1
decrypted message is 70c164a57d6bc32dd123392e2ce7914c482b850ded423583f49ac6328e8d0f9ddf8b441ea2aad6bafb0000000000030da3f1b913122991662c665558455c83f11f37eb9a010000000100000225
peerIdx is 1
```

As can be seen from the log, it didn't attempt to reconnect when it lost connection until I manually intervened to reconnect. 

@gertjaap

**Comment by metalicjames** [comment] 2018-06-13 23:47
Related to #190, autoReconnect will try to use IPv6 even when only IPv4 is available and the IPv4 address was used to connect previously. 

```
Reconnecting to known peers
Could not restore connection to ln1gg6c8ay6ccegarg0nh0ck3q7524ddwhmzhmkk4: dial tcp: address 2001:41d0:e:864::1:2448: too many colons in address
no peer Done, tried 1 hosts
```

**Comment by gertjaap** [comment] 2018-06-27 22:40
If the card is moved to `Done` can we close this issue? @metalicjames ?

**Comment by Varunram** [comment] 2018-07-13 19:01
@gertjaap This should be closed :)

**Comment by Varunram** [comment] 2018-08-03 14:40
@gertjaap reminder!

**Closed** 2018-09-11 09:44 UTC
